# -*- coding: utf-8 -*-
"""Exploratory analysis simulated.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1almtmZ4JOR2YMWL5nHJeh8NFkgGJiPv3
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Set seed for reproducibility
np.random.seed(42)

# Task 1: Generate synthetic dataset
data = {
    'CustomerID': range(1, 501),
    'Age': np.random.randint(20, 66, size=500),
    'AnnualIncome': np.random.randint(30000, 120001, size=500),
    'SpendingScore': np.random.randint(1, 101, size=500)
}

df = pd.DataFrame(data)

# Save to CSV internally
df.to_csv('customer_spending_data.csv', index=False)
print("Dataset generated and saved successfully.")
# Data Cleaning and Preparation



# Task 2: Data Cleaning
# Verify data types and check for nulls
print(df.info())
print("\nMissing Values:\n", df.isnull().sum())

# Ensure Age is an integer (though generated as such, good practice to verify)
df['Age'] = df['Age'].astype(int)
# Descriptive Statistics
# step calculates the mean, median, standard deviation, and range for your numerical columns.

# Task 3: Descriptive Statistics
stats_cols = ['Age', 'AnnualIncome', 'SpendingScore']
descriptive_stats = df[stats_cols].describe().transpose()

# Add Median explicitly as .describe() includes 50% (which is the median)
print("Descriptive Statistics Summary:\n", descriptive_stats)
# Visualization
# Histogram for Income and a Scatter Plot for Age vs. Spending Score.


# Task 4: Visualization
plt.figure(figsize=(14, 6))

# Plot 1: Histogram of Annual Income
plt.subplot(1, 2, 1)
sns.histplot(df['AnnualIncome'], bins=20, kde=True, color='teal')
plt.title('Distribution of Annual Income')
plt.xlabel('Annual Income ($)')

# Plot 2: Scatter Plot of Age vs Spending Score
plt.subplot(1, 2, 2)
sns.scatterplot(data=df, x='Age', y='SpendingScore', color='coral')
plt.title('Age vs. Spending Score')
plt.xlabel('Age')
plt.ylabel('Spending Score (1-100)')

plt.tight_layout()
plt.show()

